Add Pure as submodule & handle submodule for first-run/update + Fix source functions
❯ git submodule add https://github.com/sindresorhus/pure.git
submodules/terminal/pure
❯ git submodule init
❯ git submodule update

diff --git a/dotfilesception/zshrc b/dotfilesception/zshrc
--- a/dotfilesception/zshrc
+++ b/dotfilesception/zshrc
@@ -18,6 +18,7 @@ setopt HIST_NO_STORE
 setopt HIST_SAVE_NO_DUPS
 setopt HIST_VERIFY
 setopt INC_APPEND_HISTORY
+#setopt PRINT_EXIT_VALUE
 
 export LC_CTYPE=en_US.UTF-8
 export LC_ALL=en_US.UTF-8
@@ -34,10 +35,16 @@ fi
 
 export PATH=$DIR_DOTFILES/bin:$PATH
 
-PURE_CMD_MAX_EXEC_TIME=1
-fpath=("$DIR_DOTFILES/backpack/functions" $fpath)
+if ! ls /usr/local/share/zsh/site-functions/prompt_pure_setup &> /dev/null
+then
+	ln -s "$DIR_DOTFILES/submodules/terminal/pure/pure.zsh" /usr/local/share/zsh/site-functions/prompt_pure_setup
+fi
+fpath=( "/usr/local/share/zsh/site-functions" $fpath )
 autoload -U promptinit && promptinit
+#PURE_CMD_MAX_EXEC_TIME=2
 prompt pure
+# add %F{red}%(?..[%?] )%f to include exit code [code]
+PROMPT='%(?.%F{green}.%F{red}❯%F{green})❯%f '
 
 export EDITOR=subl
 
@@ -61,6 +68,7 @@ export COPYFILE_DISABLE=true
 ##
 # Source topic files
 ##
+source $DIR_DOTFILES/backpack/functions.sh
 
 # load other aliases
 for source in `find $DIR_DOTFILES -maxdepth 2 -name \*.aliases`
